config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :playlists
  resources :favourites
  resources :albums
  resources :songs

  get 'home/contact'
  root 'home#index'
  get 'playlists', to: 'playlists#show'
  post 'playlist/searchsongs', to: 'playlists#search_song'
  post 'playlist/addsongs', to: 'playlists#add_song'
  post 'playlist/removesongs', to: 'playlists#remove_song'
  post 'playlist/removesongs', to: 'playlists#remove_song'
  get  'home/test', to: 'home#email_contact'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/playlist.rb
class Playlist < ApplicationRecord
    has_and_belongs_to_many :songs
    belongs_to :user
    #validates :song_name, presence: true

end

app/models/song.rb
class Song < ApplicationRecord
    has_and_belongs_to_many :playlists

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

         has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    def contact_email
        contact_mailer.with(name: name, email: email, phone: phone, message: message).send_email
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def contact 
  end

  def email_contact
    name = params[:name]
    email = params[:email]
    phone = params[:phone]
    message = params[:message]
    ContactMailer.send_email(name, email, phone, message).deliver_now

  end


  def about
  end
  


end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: %i[ show edit update destroy ]
  # If user is not authenticated don't allow them access to change playlists
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :update, :destroy]


  # GET /playlists or /playlists.json
  def index
    @playlists = Playlist.all
  end

  # search for a song in the database using the search query
  def search_song
    @songs = Song.where("title like ?", params["search_term"]) if params["search_term"].present?
    @playlist = params["playlist_id"]
  end

  # Checks if you are the correct user for the playlist if not you get prompted with a message
  def correct_user
    @playlist = current_user.playlists.find_by(id: params[:id])
    redirect_to playlists_path, notice: "Not Aurthorized To Edit This Playlist" if @playlist.nil?
  end

  # add a song to a playlist
  def add_song
    playlist_id = params["playlist_id"]
    playlist_to_add = Playlist.find(playlist_id)

    song_id = params["song_id"]
    song_to_add = Song.find(song_id)
    
    playlist_to_add.songs << song_to_add

  end

  # remove a song to a playlist
  def remove_song
    playlist_id = params["playlist_id"]
    playlist= Playlist.find(playlist_id)

    song_id = params["song_id"]
    song_to_remove = Song.find(song_id)
    
    playlist.songs.delete(song_to_remove)

  end

  # GET /playlists/1 or /playlists/1.json
  def show
    playlist_id = params["id"]
    playlist_found = Playlist.find(playlist_id)
    
    @playlist_songs = playlist_found.songs

  end

  # GET /playlists/new
  def new
    #@playlist = Playlist.new
    @playlist = current_user.playlists.build
  end

  # GET /playlists/1/edit
  def edit
  end

  # POST /playlists or /playlists.json
  def create
    puts "In create method"
    #@playlist = Playlist.new(playlist_params)
    # Ties the current user to when the playlist is created
    @playlist = current_user.playlists.build(playlist_params)

    respond_to do |format|
      if @playlist.save
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully created." }
        format.json { render :show, status: :created, location: @playlist }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /playlists/1 or /playlists/1.json
  def update
    respond_to do |format|
      if @playlist.update(playlist_params)
        format.html { redirect_to playlist_url(@playlist), notice: "Playlist was successfully updated." }
        format.json { render :show, status: :ok, location: @playlist }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @playlist.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /playlists/1 or /playlists/1.json
  def destroy
    @playlist.destroy

    respond_to do |format|
      format.html { redirect_to playlists_url, notice: "Playlist was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def playlist_params
      params.require(:playlist).permit(:playlist_name, :song_id, :search, :user_id)
    end

    
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: %i[ show edit update destroy ]

  # GET /songs or /songs.json
  def index
    @songs = Song.all
  end

  # GET /songs/1 or /songs/1.json
  def show
  end

  # GET /songs/new
  def new
    @song = Song.new
  end

  # GET /songs/1/edit
  def edit
  end

  # POST /songs or /songs.json
  def create
    @song = Song.new(song_params)

    respond_to do |format|
      if @song.save
        format.html { redirect_to song_url(@song), notice: "Song was successfully created." }
        format.json { render :show, status: :created, location: @song }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /songs/1 or /songs/1.json
  def update
    respond_to do |format|
      if @song.update(song_params)
        format.html { redirect_to song_url(@song), notice: "Song was successfully updated." }
        format.json { render :show, status: :ok, location: @song }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @song.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /songs/1 or /songs/1.json
  def destroy
    @song.destroy

    respond_to do |format|
      format.html { redirect_to songs_url, notice: "Song was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_song
      @song = Song.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def song_params
      params.require(:song).permit(:title, :artist, :album)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/home/_footer.html.erb
<!-- Footer for page stylised with bootstrap -->
<footer class="mt-auto">
    <body class="d-flex flex-column min-vh-100">
    <ul class="nav justify-content-center border-bottom pb-3 mb-3">
      <li class="nav-item"><%= link_to 'Home', root_path, class:"nav-link px-2 text-muted" %></li>
      <li class="nav-item"><%= link_to 'Songs', songs_path, class:"nav-link px-2 text-muted" %></li>
      <li class="nav-item"><%= link_to 'Playlists', playlists_path, class:"nav-link px-2 text-muted" %>   </li>
      <li class="nav-item"><%= link_to 'Contact Us', home_contact_path , class:"nav-link px-2 text-muted" %></li>
    </ul>
    <p class="text-center text-muted">Podlite</p>
    </body>
  </footer>

app/views/home/_header.html.erb
<!-- Bootstrap Element for nav bar!-->
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
  <!-- Home Button leads you to home page!-->
    <%= link_to 'Podlite', root_path, class:"navbar-brand"%>
    

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
      <!-- Link to each item in navbar-->
        <li class="nav-item">
            <%= link_to "Contact Us", home_contact_path, class:"nav-link" %>
        </li>
        
        <li class="nav-item">
            <%= link_to "Songs", songs_path, class:"nav-link" %>
        </li>

        <li class="nav-item">
            <%= link_to "Playlists", playlists_path, class:"nav-link" %>
        </li>

        <%if user_signed_in? %>

            <li class="nav-item">
                <%= link_to "New Song", new_song_path, class:"nav-link" %>
            </li>


            <li class="nav-item">
                <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class:"btn btn-dark" %>
            </li>

            <li class="nav-item">
                <%= link_to "Edit Profile", edit_user_registration_path, class:"nav-link" %>
            </li>

        <% else %>

           <li class="nav-item">
               <%= link_to "Sign Up", new_user_registration_path, class:"nav-link" %>
           </li>

           <li class="nav-item">
               <%= link_to "Sign In", new_user_session_path, class:"nav-link" %>
           </li>
        <% end %>        
          
      </ul>

    </div>
  </div>
</nav>

app/views/home/contact.html.erb
<%= form_with url: "test", method: :get, local: true do |form| %>


<div class="form-group">
    <%= form.label :name %> 
    <%= form.text_field :name, class: "form-control"  %> 
</div>

<div class="form-group">
    <%= form.label  :email %> 
    <%= form.email_field  :email, class: "form-control" %> 
</div>

<div class="form-group">
    <%= form.label :phone %> 
    <%= form.text_field :phone, class: "form-control" %> 
</div>

<div class="form-group">
    <%= form.label :message %> 
    <%= form.text_field :message, class: "form-control " %> 
</div>



<%= form.submit "Submit", class:"btn btn-danger my-2" %> </td>
<% end %>   

app/views/home/email_contact.html.erb
<div class="alert alert-warning" role="alert">
  Email has been sent.
</div>

app/views/home/index.html.erb
<!-- Intro text and image -->
<section id="intro">
    <div class="container-md my-5 p-3 rounded-pill border border-5 shadow-sm">
        <div class="row justify-content-center align-items-center">
            <div class="col-md-5 text-center text-md-start">   <!-- Default sized screen text is in the center then as the screen gets larger it will be moved to the left -->
                <h1>
                    <div class="display-1">Podlite</div>
                    <div class="display-5">Your portable music collection</div>
                </h1>
                <p class="lead my-4 text-muted">Live your day with music</p>
                <%= link_to 'Sign up for free!', new_user_registration_path, class:"btn btn-primary btn-lg shadow" %>
                <%= link_to 'Already have an account? Login', new_user_session_path, class:"btn btn-success btn-lg my-2 shadow" %>
            </div>
        </div>
    </div> 
</section>







    





    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
</body>
</html>

app/views/layouts/_alerts.html.erb
<div class="alert alert-warning alert-dismissible fade show" role="alert">
  <%= notice %>
  <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
</div>

app/views/layouts/application.html.erb
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Podlite</title>

    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
  </head>
  <body>

    <%= render 'home/header' %>
    <div class=" my-3 container">
        <!-- Alert for when creating a new resource-->
      <% if notice%>
        <%= render 'layouts/alerts'%>
      <% end %>
    <!-- Loads page content in the body!-->
    <%= yield %>
    </div>
    <%= render 'home/footer' %>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-A3rJD856KowSb7dwlZdYEkO39Gagi7vIsF0jrRAoQmDKKtQBHUuLZ9AsSv4jD4Xa" crossorigin="anonymous"></script>
  </body>
</html>

app/views/layouts/contact.html.erb
<h1>Contact</h1> <br>
<p><%=@message%></p><br>
<p>Name: <%=@name%></p>
<p>Email: <%=@email%></p>
<p>Phone: <%=@phone%></p>
<p>Thanks,</p>
<p><%=@name%></p>

app/views/playlists/_form.html.erb
      <!-- Loop to go through each item in resource-->
<%= form_with(model: playlist) do |form| %>
  <% if playlist.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(playlist.errors.count, "error") %> prohibited this playlist from being saved:</h2>

      <ul>
        <% playlist.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

        <!-- Input boxes for each attribute with example inputs present inside-->
  <div class="form-group my-2">
    <%= form.text_field :playlist_name, class:"form-control", placeholder:"Runaway" %>
  </div>
        <!-- Retrieving current users id but keeps it hidden-->

    <%= form.hidden_field :user_id, value: current_user.id %>
  
        <!-- Submit button -->
  <div>
    <%= form.submit class:"btn btn-secondary my-2" %>
  </div>
<% end %>

app/views/playlists/add_song.html.erb
<p>Added song to playlist</p>

<%= link_to "Back to playlists", playlists_path, class:"btn btn-dark" %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Show', @playlist,  class:"btn btn-dark"  %> 
<%= link_to 'Back', playlists_path,  class:"btn btn-danger"  %>

app/views/playlists/index.html.erb
      <!-- Created table using bootstrap to display resource-->
<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Playlist Name</th>
      <th>User ID</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>
  
        <!-- Loop that goes through each item in resource-->
  <tbody>
    <% @playlists.each do |playlist| %>
      <tr>
        <td><%= playlist.playlist_name %></td>
        <td><%= playlist.user_id %></td>
        <td><%= link_to 'Show', playlist, class:"btn btn-sm btn-success my-2"  %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist), class:"btn btn-sm btn-dark my-2" %></td>          
        <td><%= link_to 'Delete', playlist, class:"btn btn-sm btn-danger my-2", method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

      <!-- Button to add a new record -->

<%= link_to 'New Playlist', new_playlist_path, class:"btn btn-primary" %>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form', playlist: @playlist %>

<%= link_to 'Back', playlists_path, class:"btn btn-danger"  %>

app/views/playlists/remove_song.html.erb
<p>Removed song from playlist</p>

<%= link_to "Back to playlists", playlists_path, class:"btn btn-dark" %>

app/views/playlists/search_song.html.erb
    

    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>

        <%= form_with url: "/playlist/addsongs", method: :post, local: true do |form| %>

        <%= form.hidden_field :song_id, value: song.id %> 
        <%= form.hidden_field :playlist_id, value: @playlist %> 
        <%= form.submit "Add to Playlist" %>

        <% end %>



    <%end%>


    

app/views/playlists/show.html.erb
      <!-- Simple container that displays information about each item-->
<div class="container m-3 ">
  <h1 class="display-4">

  </h1>

  <%= form_with url: "/playlist/searchsongs", method: :post, local: true do |form| %>
  <%= form.label :query, "What song would you like to add?:  " %>
  <%= form.text_field :search_term, class:"form-control w-25" %>

  <%= form.hidden_field :playlist_id, value: @playlist.id %> 
  <%= form.submit "SEARCH", class:"btn btn-sm btn-outline-primary my-1" %>

  <% end %>


<%if @playlist_songs.empty? %>

  <p>Playlist is Empty...</p>

<%else%>

  <p><%@playlist_songs.inspect%></p>

        <!-- Created table using bootstrap to display resource-->
  <table class="table table-striped table-bordered table-hover">
    <thead class="thead-dark">
      <tr>
        <th>Title</th>
        <th>Artist</th>
        <th>Album</th>
        <th></th>
      </tr>
    </thead>
    
          <!-- Loop that goes through each item in resource-->
    <tbody>
    
      <% @playlist_songs.each do |playlist_song| %>
        <tr>
          <td><%= playlist_song.title %></td>
          <td><%= playlist_song.artist %></td>
          <td><%= playlist_song.album%></td>



          <td><%= form_with url: "/playlist/removesongs", method: :post, local: true do |form| %>

          <%= form.hidden_field :playlist_id, value: @playlist.id %> 
          <%= form.hidden_field :song_id, value: playlist_song.id%> 

          <%= form.submit "Remove", class:"btn btn-sm btn-danger my-2" %> </td>
          <% end %>    
        </tr>
      <% end %>
      
    </tbody>
  </table>

  <% end %>
 
        <!-- Buttons using bootstrap for each action-->
  <%= link_to "Edit this playlist", edit_playlist_path(@playlist), class:"btn btn-secondary" %> 
  <%= link_to "Back to playlists", playlists_path, class:"btn btn-dark" %>
  <%= button_to "Delete this playlist", @playlist, class:"btn btn-danger my-2" , method: :delete %>

</div> 

app/views/songs/_form.html.erb
      <!-- Loop to go through each item in resource-->
<%= form_with(model: song) do |form| %>
  <% if song.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(song.errors.count, "error") %> prohibited this song from being saved:</h2>

      <ul>
        <% song.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

        <!-- Input boxes for each attribute with example inputs present inside-->
  <div class="form-group my-2">
    <%= form.text_field :title, class:"form-control", placeholder:"Runaway" %>
  </div>

  <div class="form-group my-2">
    <%= form.text_field :artist, class:"form-control", placeholder:"Kanye West"   %>
  </div>

  <div class="form-group my-2">
    <%= form.text_field :album, class:"form-control", placeholder:"My Beautiful Dark Twisted Fantasy"  %>
  </div>
  
        <!-- Submit button -->
  <div>
    <%= form.submit class:"btn btn-secondary my-2" %>
  </div>
<% end %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Show', @song,  class:"btn btn-dark"  %> 
<%= link_to 'Back', songs_path,  class:"btn btn-danger" %>

app/views/songs/index.html.erb
      <!-- Created table using bootstrap to display resource-->

<table class="table table-striped table-bordered table-hover">
  <thead class="thead-dark">
    <tr>
      <th>Title</th>
      <th>Artist</th>
      <th>Album</th>
    </tr>
  </thead>

        <!-- Loop that goes through each item in resource-->
  <tbody>
    <% @songs.each do |song| %>
      <tr>
        <td><%= song.title %></td>
        <td><%= song.artist %></td>
        <td><%= song.album %></td>
        <td><%= link_to 'Show', song, class:"btn btn-sm btn-success my-2" %></td>
        <td><%= link_to 'Edit', edit_song_path(song), class:"btn btn-sm btn-dark my-2" %></td>          
        <td><%= link_to 'Delete', song, method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-sm btn-danger my-2" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

      <!-- Button to add a new record -->

<%= link_to 'New song', new_song_path, class:"btn btn-primary" %>

<br>

app/views/songs/new.html.erb
<h1>Add New Song</h1>

<%= render 'form', song: @song %>

<%= link_to 'Back', songs_path, class:"btn btn-danger" %>

app/views/songs/show.html.erb
      <!-- Simple container that displays information about each item-->
<div class="container m-3 ">
  <h1 class="display-4">
    <%=  @song.title %> 


  </h1>
  <p>
    <%=  @song.title %> |  
    <%=  @song.artist %> |
    <%=  @song.album %> | 
  </p>

        <!-- Buttons using bootstrap for each action-->
  <%= link_to "Edit this song", edit_song_path(@song), class:"btn btn-secondary" %> 
  <%= link_to "Back to songs", songs_path, class:"btn btn-dark" %>
  <%= button_to "Destroy this song", @song, class:"btn btn-danger my-2" , method: :delete %>

</div> 